# Generated by Django 4.2.6 on 2023-10-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('venue_open', models.DateField()),
                ('date_use', models.DateField(auto_now_add=True)),
                ('date_return', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('display_authors', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=255)),
                ('thumbnail', models.TextField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BacaDiTempat.bookuser')),
            ],
        ),
    ]
