# Generated by Django 4.2.6 on 2023-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BacaDiTempat', '0002_venue_alter_bookvenue_venue_delete_bookuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.AddField(
            model_name='venue',
            name='book_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='person_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='date_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
