# Generated by Django 4.2.6 on 2023-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BacaDiTempat', '0006_venue_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='map_location',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
