# Generated by Django 4.2.6 on 2023-10-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BacaDiTempat', '0007_venue_map_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='book_amount',
        ),
        migrations.AddField(
            model_name='venue',
            name='rent_book',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='return_book',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
