# Generated by Django 4.2.6 on 2023-10-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('google_id', models.CharField(max_length=255)),
                ('etag', models.CharField(max_length=255)),
                ('selfLink', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('publisher', models.CharField(max_length=255)),
                ('publishedDate', models.DateField()),
                ('description', models.TextField()),
                ('textReadingMode', models.BooleanField()),
                ('imageReadingMode', models.BooleanField()),
                ('pageCount', models.PositiveIntegerField()),
                ('printType', models.CharField(max_length=255)),
                ('categories', models.TextField()),
                ('maturityRating', models.CharField(max_length=255)),
                ('allowAnonLogging', models.BooleanField()),
                ('contentVersion', models.CharField(max_length=255)),
                ('containsEpubBubbles', models.BooleanField()),
                ('containsImageBubbles', models.BooleanField()),
                ('smallThumbnail', models.URLField()),
                ('thumbnail', models.URLField()),
                ('language', models.CharField(max_length=255)),
                ('previewLink', models.URLField()),
                ('infoLink', models.URLField()),
                ('canonicalVolumeLink', models.URLField()),
            ],
        ),
    ]
