# Generated by Django 4.2.6 on 2023-10-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=50)),
                ('forumsDescription', models.CharField(max_length=50)),
                ('bookPicture', models.ImageField(upload_to='reviewimages/')),
            ],
        ),
    ]
