# Generated by Django 4.2.6 on 2023-10-25 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliofilia', '0002_forum_userreview_alter_forum_bookname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='dateOfPosting',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
