# Generated by Django 4.2.6 on 2023-10-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliofilia', '0009_alter_forumreply_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
