    # Generated by Django 4.2.6 on 2023-10-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliofilia', '0011_forumreply_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumreply',
            name='parent_id',
        ),
    ]
