# Generated by Django 4.2.6 on 2023-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliofilia', '0012_remove_forumreply_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='repliesTotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
