# Generated by Django 4.2.6 on 2023-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliofilia', '0022_alter_forumreply_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
