# Generated by Django 4.2.7 on 2023-12-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userbook'),
        ('Bibliofilia', '0024_alter_forum_userreview_alter_forumreply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='userbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userbook'),
        ),
    ]
