# Generated by Django 4.2.7 on 2023-12-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliofilia', '0025_forum_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='BookName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='forumsDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
