# Generated by Django 4.2.6 on 2023-10-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('opening_hours', models.CharField(max_length=50)),
                ('rentable', models.PositiveIntegerField()),
                ('returnable', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StationBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('display_authors', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=255)),
                ('thumbnail', models.TextField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimanaSajaKapanSaja.station')),
            ],
        ),
    ]
