# Generated by Django 4.2.6 on 2023-10-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimanaSajaKapanSaja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='map_location',
            field=models.ImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
