# Generated by Django 4.2.6 on 2023-10-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimanaSajaKapanSaja', '0002_station_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='map_location',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
